\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Tarea Ejercicios con LaTeX, R y Markdown},
            pdfauthor={Carla Romero Sansano},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Tarea Ejercicios con LaTeX, R y Markdown}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Carla Romero Sansano}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{24 de agosto de 2019}


\begin{document}
\maketitle

\section{Introducción}\label{introduccion}

En primer lugar, debéis reproducir este documento tal cual está.
Necesitaréis instalar MiKTeX y Texmaker. A continuación de cada
pregunta, tenéis que redactar vuestras respuestas de manera correcta y
argumentada, indicando qué hacéis, por qué, etc. Si se os pide utilizar
instrucciones de R, tendréis que mostrarlas todas en chunks. El objetivo
de esta tarea es que os familiaricéis con los documentos Markdown, las
fórmulas en \(\LaTeX\) y los chunks de R. Y, de lo más importante, que
os acostumbréis a explicar lo que hacéis en cada momento.

\section{Preguntas}\label{preguntas}

\subsection{Pregunta 1}\label{pregunta-1}

Realizad los siguientes productos de matrices siguiente en R:
\[A \cdot B\] \[B \cdot A\] \[\left(A \cdot B \right)^t\]
\[B^t \cdot A\] \[\left (A \cdot B \right)^{-1}\] \[A^{-1} \cdot B^{t}\]
donde
\[A=\begin{pmatrix} 1 & 2 & 3 & 4 \\4 & 3 & 2 & 1\\0 & 1 & 0 & 2\\3 & 0 & 4 & 0 \end{pmatrix}\quad B=\begin{pmatrix} 4 & 3 & 2 & 1\\0 & 3 & 0 & 4\\1 & 2 & 3 & 4\\0 & 1 & 0 & 2 \end{pmatrix}\]

Finalmente, escribe haciendo uso de \(\LaTeX\ \) el resultado de los dos
primeros productos de forma adecuada.

Respuesta:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Primero creo las dos matrices con las que vamos a trabajar}
\NormalTok{A =}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{0}\NormalTok{))}
\NormalTok{A}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    4
## [2,]    4    3    2    1
## [3,]    0    1    0    2
## [4,]    3    0    4    0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{B =}\StringTok{ }\KeywordTok{rbind}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{4}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\NormalTok{B}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,]    4    3    2    1
## [2,]    0    3    0    4
## [3,]    1    2    3    4
## [4,]    0    1    0    2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Una vez creadas las dos matrices A y B, llevo a cabo los productos que nos indica el ejercicio}
\NormalTok{A}\OperatorTok{%*%}\NormalTok{B }\CommentTok{#Producto matricial}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,]    7   19   11   29
## [2,]   18   26   14   26
## [3,]    0    5    0    8
## [4,]   16   17   18   19
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{B}\OperatorTok{%*%}\NormalTok{A }\CommentTok{#Producto matricial}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,]   19   19   22   23
## [2,]   24    9   22    3
## [3,]   21   11   23   12
## [4,]   10    3   10    1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t}\NormalTok{(A}\OperatorTok{%*%}\NormalTok{B) }\CommentTok{#Transpuesta del producto A·B}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,]    7   18    0   16
## [2,]   19   26    5   17
## [3,]   11   14    0   18
## [4,]   29   26    8   19
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{t}\NormalTok{(B)}\OperatorTok{%*%}\NormalTok{A }\CommentTok{#Transpuesta de B multiplicada por A}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4]
## [1,]    4    9   12   18
## [2,]   18   17   19   19
## [3,]    2    7    6   14
## [4,]   23   18   19   16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{solve}\NormalTok{(A}\OperatorTok{%*%}\NormalTok{B) }\CommentTok{#Matriz inversa del producto A·B}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       [,1]  [,2]  [,3]  [,4]
## [1,] -1.66 -0.65  4.52  1.52
## [2,]  1.60  0.80 -4.60 -1.60
## [3,]  1.02  0.35 -2.84 -0.84
## [4,] -1.00 -0.50  3.00  1.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{solve}\NormalTok{(A)}\OperatorTok{%*%}\KeywordTok{t}\NormalTok{(B) }\CommentTok{#Inversa de A por la transpuesta de B}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               [,1] [,2] [,3] [,4]
## [1,]  6.000000e-01  2.4  6.4  1.2
## [2,] -3.330669e-16 -2.0 -7.0 -1.2
## [3,] -2.000000e-01 -0.8 -3.8 -0.4
## [4,]  1.000000e+00  1.0  5.0  0.6
\end{verbatim}

Resultado de los dos primeros productos en \(\LaTeX\):
\[A \cdot B = \begin{pmatrix} 7 & 19 & 11 & 29\\18 & 26 & 14 & 26\\0 & 5 & 0 & 8\\16 & 17 & 18 & 19 \end{pmatrix}\]
\[B \cdot A = \begin{pmatrix}19 & 19 & 22 & 23\\24 & 9 & 22 & 3\\21 & 11 & 23 & 12\\10 & 3 & 10 & 1 \end{pmatrix}\]

\subsection{Pregunta 2}\label{pregunta-2}

Considerad en un vector los números de vuestro DNI y llamadlo
\texttt{dni}. Por ejemplo, si vuestro DNI es 54201567K, vuestro vector
será \[dni = \left(5,4,2,0,1,5,6,7 \right)\] Definid el vector en R.
Calculad con R el vector \texttt{dni} al cuadrado, la raíz cuadrado del
vector \texttt{dni} y, por último, la suma de todas las cifras del
vector \texttt{dni}. Finalmente, escribid todos estos vectores también
en \(\LaTeX\)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dni =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DecValTok{7}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{0}\NormalTok{) }\CommentTok{#Primero defino el vector}
\NormalTok{dni}\OperatorTok{^}\DecValTok{2} \CommentTok{#Calculo el cuadrado del vector elevándolo a 2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 49 16  9 81  9 36  4  0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dni}\OperatorTok{*}\NormalTok{dni }\CommentTok{# O multiplicándolo por sí mismo}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 49 16  9 81  9 36  4  0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{round}\NormalTok{(}\KeywordTok{sqrt}\NormalTok{(dni),}\DecValTok{2}\NormalTok{) }\CommentTok{#Raíz cuadrada del vector redondeada a 2 cifras decimales}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.65 2.00 1.73 3.00 1.73 2.45 1.41 0.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cumsum}\NormalTok{(dni)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  7 11 14 23 26 32 34 34
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{max}\NormalTok{(}\KeywordTok{cumsum}\NormalTok{(dni)) }\CommentTok{#Suma total de todas las cifras del vector. Utilizo la función max(), ya que la función cumsum devuelve las sumas acumuladas de los elementos del vector y el último elemento (el máximo) es la suma total. }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 34
\end{verbatim}

Vector original: \[dni = \left(7,4,3,9,3,6,2,0 \right)\] Vector al
cuadrado: \[dni^{2}=\left(49,16,9,81,9,36,4,0 \right)\] Raíz cuadrada
del vector:
\[\sqrt{dni}=\left(2.65, 2, 1.73, 3, 1.73, 2.45, 1.41, 0 \right)\] Suma
de todas las cifras del vector: \[\sum{dni}=34\] Sumas acumuladas del
vector: \[\sum_{i=0}^{n}dni = \left(7,11,14,23,26,32,34,34 \right)\]

\subsection{Pregunta 3}\label{pregunta-3}

Considerad el vector de las letras de vuestro nombre y apellido.
Llamadlo \texttt{name}. Por ejemplo, en mi caso sería
\[nombre=\left(M,A,R,I,A,S,A,N,T,O,S \right)\] Definid dicho vector en
R. Calculad el subvector que solo contenga vuestro nombre. Calculad
también el subvector que contenga solo vuestro apellido. Ordenadlo
alfabéticamente. Cread una matriz con este vector. Redactad todos
vuestros resultados y utilizad \(\LaTeX\) cuando toque.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{name =}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"C"}\NormalTok{,}\StringTok{"A"}\NormalTok{,}\StringTok{"R"}\NormalTok{,}\StringTok{"L"}\NormalTok{,}\StringTok{"A"}\NormalTok{,}\StringTok{"R"}\NormalTok{,}\StringTok{"O"}\NormalTok{,}\StringTok{"M"}\NormalTok{,}\StringTok{"E"}\NormalTok{,}\StringTok{"R"}\NormalTok{,}\StringTok{"O"}\NormalTok{) }\CommentTok{#Defino el vector con mi nombre y apellido}
\NormalTok{name[}\DecValTok{1}\OperatorTok{:}\DecValTok{5}\NormalTok{] }\CommentTok{#Subvector solo con mi nombre}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "C" "A" "R" "L" "A"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{name[}\DecValTok{6}\OperatorTok{:}\DecValTok{11}\NormalTok{] }\CommentTok{#Subvector solo con mi apellido}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "R" "O" "M" "E" "R" "O"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sort}\NormalTok{(name) }\CommentTok{#Vector ordenado alfabéticamente}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "A" "A" "C" "E" "L" "M" "O" "O" "R" "R" "R"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nameMatrix =}\StringTok{ }\KeywordTok{matrix}\NormalTok{(name, }\DataTypeTok{nrow =} \DecValTok{2}\NormalTok{, }\DataTypeTok{byrow =}\NormalTok{ T) }\CommentTok{#Como el total de elementos no es múltiplo del número de filas, defino una matriz con una "C" repetida al final}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in matrix(name, nrow = 2, byrow = T): la longitud de los datos [11]
## no es un submúltiplo o múltiplo del número de filas [2] en la matriz
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nameMatrix}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,] "C"  "A"  "R"  "L"  "A"  "R" 
## [2,] "O"  "M"  "E"  "R"  "O"  "C"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nameMatrix2 =}\StringTok{ }\KeywordTok{matrix}\NormalTok{(name,}\DataTypeTok{ncol =} \DecValTok{2}\NormalTok{, }\DataTypeTok{nrow =} \DecValTok{5}\NormalTok{, }\DataTypeTok{byrow =}\NormalTok{ F) }\CommentTok{#Aquí defino otra matriz que según el número de columnas que indico. Como la longitud del vector no es múltiplo del número de filas, en esta ocasión se elimina la última letra de mi apellido.}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in matrix(name, ncol = 2, nrow = 5, byrow = F): la longitud de los
## datos [11] no es un submúltiplo o múltiplo del número de filas [5] en la
## matriz
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nameMatrix2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1] [,2]
## [1,] "C"  "R" 
## [2,] "A"  "O" 
## [3,] "R"  "M" 
## [4,] "L"  "E" 
## [5,] "A"  "R"
\end{verbatim}

Las respuestas en \(\LaTeX\) quedarían de la siguiente forma: El vector
con mi nombre y primer apellido
\[name=\left(C,A,R,L,A,R,O,M,E,R,O \right)\] El subvector con mi nombre
\[name=\left(C,A,R,L,A)\right)\] El subvector con mi apellido
\[name=\left(R,O,M,E,R,O\right)\] Vector ordenado alfabéticamente
\[name=\left(A,A,C,E,L,M,O,O,R,R,R\right)\] Matriz 1 con mi nombre y
apellido
\[nameMatrix =\begin{pmatrix}"C" & "A" & "R" & "L" & "A" & "R"\\"O" & "M" & "E" & "R" & "O" & "C"\end{pmatrix}\]
Matriz 2 con mi nombre y apellido
\[nameMatrix2=\begin{pmatrix}"C" & "R"\\"A" & "O"\\"R" & "M"\\"L" & "E"\\"A" & "R"\end{pmatrix}\]


\end{document}
